name: Docker CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build image from Dockerfile
      run: docker build --tag django-docker:latest .
    - name: Run image
      run: docker run -e SECRET_KEY="${{ secrets.SECRET_KEY }}" -e DEBUG="${{ secrets.DEBUG }}" -p 8080:8080 -d django-docker:latest
    - name: Test Container
      uses: wei/curl@v1
      with:
        args: --retry 10 --retry-connrefused http://localhost:8080/
