name: Docker CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build image from Dockerfile
      run: docker build --tag django-docker:latest .
    - name: Add environment variables to .env file
      run: |
        echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
        echo "DEBUG=${{ secrets.DEBUG }}" >> .env
    - name: Run container
      run: docker run -d --name django-docker --env-file .env --publish 8080:8080 django-docker:latest
    - name: Test container
      run: docker run --network container:django-docker appropriate/curl --retry 10 --retry-delay 5 --retry-connrefused http://localhost:8080/
