name: Docker CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build image from Dockerfile
      run: docker build --tag django-docker:latest .
    - name: Run image
      run: docker run -d -e SECRET_KEY="${{ secrets.SECRET_KEY }}" --name django-docker django-docker:latest
    - name: Test Container
      run: docker run --network container:django-docker appropriate/curl --retry 10 --retry-connrefused http://localhost:8080/
