name: Build Docker Image

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: docker build --tag django-docker:latest .
    - name: Run
      run: docker run -e SECRET_KEY="${{ secrets.SECRET_KEY }}" -e DEBUG="${{ secrets.DEBUG }}" -p 8080:8080 -d django-docker:latest
    - name: Test
      uses: wei/curl@v1
      with:
        args: -X GET http://localhost:8080/
